-- -- One-time migration: kolom persentase komisi di bronze dari INT64 -> FLOAT64.
-- -- Dipicu oleh normalisasi persen komisi yang kini bisa menghasilkan desimal
-- -- (mis. '7,5%' -> 7.5), sehingga append pandas_gbq gagal pada kolom INTEGER lama.
-- -- INT64 -> FLOAT64 tidak bisa lewat ALTER; pakai CTAS agar history terjaga.
-- CREATE OR REPLACE TABLE `database-sigma.Testing.bronze_affiliate` AS
-- SELECT * REPLACE(
--   CAST(persentase_komisi_standar       AS FLOAT64) AS persentase_komisi_standar,
--   CAST(persentase_komisi_iklan_belanja AS FLOAT64) AS persentase_komisi_iklan_belanja
-- )
-- FROM `database-sigma.Testing.bronze_affiliate`;
